### ISSUE TITLE
sshpk-agent fails to parse ed25519 keys

### ISSUE THREAD

**Issue by bahamat** [arekinath/node-sshpk-agent#1]
Using sshpk-agent in conjunction with node-smartdc, node-manta and node-triton, if I have my ed25519 key loaded into the agent it can't parse the data returned form ssh-agent.. This is compounded by the fact that my keys are encrypted so it can't fall back to the disk file.

**Comment by arekinath** [comment]
I repro'd this locally with an ED25519 key in my agent.

`sshpk` now has support for ED25519 keys (though of course they're not very useful for anything but fingerprinting and conversion, since `crypto` can't sign or verify with them), and this now seems to all be working properly.

Please let me know if you have any more issues.
